### ISSUE TITLE
Set architecture type to native

### ISSUE THREAD

**Issue by chris3k** [vanklompf/BlogSrc#1]
https://github.com/vanklompf/BlogSrc/blob/dcf54180b78ffdc25241f99cd16e588b0ebb7380/PacketDescriptorsProcessing/CMakeLists.txt#L3-L4

Maybe better is to set `-march` to `native` instead of manual pick up of target architecture which might be incompatible with user arch. Also `set(CMAKE_CXX_STANDARD 11)` is a mismatch with `-std=c++17` compiler option.

**Comment by vanklompf** [comment]
Native is not exactly what I want, because I sometimes compile on different platform than run. Additionally for some reason native even locally gives worse (??) results than skylake. I will investigate it further with some tests and Godbolt but for now native it is. 
Fixed in: 37f0c8135062180c2b48784eeb913c10e77290a6
